export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/projects/investigator-copilot/overview-before-comparison.png": { width: 960, height: 248 },
  "/projects/investigator-copilot/mvp-before-mark.png": { width: 2984, height: 768 },
  "/projects/investigator-copilot/design-iteration-before.png": { width: 960, height: 74 },
  "/projects/investigator-copilot/design-iteration-1.png": { width: 960, height: 57 },
  "/projects/investigator-copilot/design-iteration-2.png": { width: 960, height: 74 },
  "/projects/investigator-copilot/design-iteration-3.png": { width: 960, height: 74 },
  "/projects/investigator-copilot/transcript-states-before.png": { width: 2872, height: 277 },
  "/projects/investigator-copilot/hover-marked-exploration.png": { width: 1993, height: 999 },
  "/projects/investigator-copilot/transcript-states-final.png": { width: 2959, height: 357 },
  "/projects/investigator-copilot/marked-segments-modal-before.png": { width: 2812, height: 769 },
  "/projects/investigator-copilot/marked-segments-panel-after.png": { width: 960, height: 428 },
  "/projects/investigator-copilot/marked-segments-card-states.png": { width: 2290, height: 638 },
  "/projects/investigator-copilot/design-system-components.png": { width: 1726, height: 812 },
  "/projects/investigator-copilot/design-tokens-naming.png": { width: 699, height: 380 },
  "/projects/investigator-copilot/other-screens.png": { width: 1926, height: 574 },
  "/projects/investigator-copilot/transcript-row-component.png": { width: 3826, height: 1580 },
  "/projects/investigator-copilot/transcript-row-iterations.png": { width: 5064, height: 585 },
};
